name: build-and-lint

# Triggers: Define when this workflows should run
# trigger on push to these branches
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'  # Specify your Node.js version
          
      - name: Install dependencies
        working-directory: server
        run: npm ci  # or yarn install --frozen-lockfile
        
      - name: Lint backend
        working-directory: server
        run: npm run lint -- --max-warnings=0 # or your specific lint command

      - name: Install frontend dependencies
        working-directory: client
        run: npm ci  # or yarn install --frozen-lockfile
        
      - name: Lint frontend
        working-directory: client
        run: npm run lint -- --max-warnings=0 # or your specific lint command

      - name: Build backend image
        run: docker build -t backend ./server
      
      - name: Build frontend image
        run: docker build -t frontend ./client